apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-git
  namespace: default
spec:
  interval: 1m
  url: https://github.com/network-charles/gitops.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kustom
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-git
  path: "./Lab\ 04/dev/kustomization"
  prune: true
  timeout: 1m
