kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950 # The k8s service port
    hostPort: 9090
    listenAddress: "0.0.0.0"
    protocol: tcp
